### ISSUE TITLE
x11-apps/compton::bruners and x11-apps picom::hasufell

### ISSUE THREAD

**Issue by Archetypic** [Bruners/exheres#8]
Hello, `x11-apps/compton` and `x11-apps/picom` are identical.

`x11-apps/compton` HOMEPAGE = https://github.com/yshui/picom

`x11-apps/picom` HOMEPAGE = https://github.com/yshui/picom

Is there anything that should be done about this?

I have [contacted](https://gogs.hasufell.de/hasufell/hasufell-repository/issues/66) the owner of `::hasufell` regarding this situation.

**Comment by Philantrop** [comment]
::hasufell is abandoned.

**Comment by Archetypic** [comment]
I suppose you mean that the repository is abandoned or just referencing `x11-apps/picom`?

**Comment by Philantrop** [comment]
> I suppose you mean that the repository is abandoned or just referencing `x11-apps/picom`?

The repository ::hasufell has been abandoned by its owner. They don't work on it anymore and, thus, might be gone at some point.

**Comment by Archetypic** [comment]
I apologize about my misunderstanding of your sentence.

**Comment by Archetypic** [comment]
The owner of `::hasufell` has responded strongly implying that the repository is not abandoned.
